<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/6 0006
 * Time: 16:38
 */

namespace app\index\controller;


use think\Controller;
use app\common\lib\exception\ApiException;
use app\common\lib\IAuth;
use think\Cache;
use think\Session;

class Base extends Controller
{
    /**
     * 用户ID
     */
    public $userId;

    /**
     * 初始化
     * @throws ApiException
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkRequestAuth();
        $this->checkLogin();
    }

    public function checkLogin(){
        $user = Session::get('blog.user_session');
        if(!$user){
            throw new ApiException(0,'暂未登陆', 200);
        }else{
            $this->userId = $user;
        }
    }

    public function checkRequestAuth(){
        $headers = request()->header();

        // 基础参数校验
        if(empty($headers['sign'])) {
            throw new ApiException(1,'sign不存在', 400);
        }

        // 需要sign
        if(!IAuth::checkSignPass($headers)) {
            throw new ApiException(1,'授权码sign失败', 401);
        }
        Cache::set($headers['sign'], 1, config('daishu.app_sign_cache_time'));

    }
}